-- Production URL과 CRON_SHARED_SECRET을 Supabase Vault에 등록한 후 실행합니다.
-- Database > Extensions에서 pg_net과 vault를 활성화합니다.
-- select vault.create_secret('https://your-domain.com/api/internal/email-worker', 'email_worker_url');
-- select vault.create_secret('replace-with-cron-secret', 'cron_shared_secret');
--
-- select cron.schedule(
--   'booth-booth-email-worker',
--   '* * * * *',
--   $$
--   select net.http_post(
--     url := (select decrypted_secret from vault.decrypted_secrets where name = 'email_worker_url'),
--     headers := jsonb_build_object(
--       'Content-Type', 'application/json',
--       'Authorization', 'Bearer ' || (select decrypted_secret from vault.decrypted_secrets where name = 'cron_shared_secret')
--     ),
--     body := '{}'::jsonb
--   );
--   $$
-- );
