import Link from 'next/link'
import { ArrowLeft, ExternalLink, ShoppingBag, Shirt } from 'lucide-react'
import { notFound } from 'next/navigation'
import { resendOrderEmailAction, updateOrderAction, updateOrderInfoAction } from '@/features/admin/actions'
import { orderStateLabel, paymentStateLabel } from '@/features/order/domain/order'
import { getOrderByNumber } from '@/server/orders/get-order'
import { Button } from '@/shared/ui/button'

type Props = { params: Promise<{ orderNumber: string }>; searchParams: Promise<{ saved?: string; emailQueued?: string; error?: string }> }

export default async function AdminOrderPage({ params, searchParams }: Props) {
  const [{ orderNumber }, query] = await Promise.all([params, searchParams])
  const order = await getOrderByNumber(orderNumber)
  if (!order) notFound()
  const overdue = order.orderState === 'payment_pending' && order.paymentState === 'pending' && Date.parse(order.paymentDueAt) < Date.now()
  return (
    <>
      <div className="admin-heading"><div><Link className="admin-back" href={{ pathname: '/admin/orders', query: { saleId: order.saleId } }}><ArrowLeft size={14} /> {order.roundNumber}차 주문 목록</Link><h1>{order.orderNumber}</h1><p>{order.saleKind === 'test' ? '테스트 주문 · ' : ''}{order.roundNumber}차 · {new Date(order.createdAt).toLocaleString('ko-KR')} 접수 · {order.customerName}</p></div></div>
      {query.saved && <div className="notice notice--success">변경 내용을 저장했습니다.</div>}
      {query.emailQueued && <div className="notice notice--success">이메일을 발송 대기열에 추가했습니다.</div>}
      {query.error && <div className="notice notice--error">저장하지 못했습니다: {query.error}</div>}
      {overdue && <div className="notice notice--warning">입금 안내 1시간이 지났습니다. 실제 입금 내역을 확인하고 입금 완료 또는 미입금 취소로 변경해주세요.</div>}
      <div className="admin-detail-grid">
        <div className="admin-panel admin-detail-summary">
          <form className="admin-order-info-form" action={updateOrderInfoAction}><input type="hidden" name="orderId" value={order.id} /><input type="hidden" name="orderNumber" value={order.orderNumber} /><input type="hidden" name="fulfillmentType" value={order.fulfillmentType} /><h2>주문자와 수령 정보</h2><div className="form-grid"><div className="field"><label>주문자</label><input name="customerName" defaultValue={order.customerName} required /></div><div className="field"><label>입금자명</label><input name="depositorName" defaultValue={order.depositorName} required /></div><div className="field"><label>휴대전화</label><input name="phone" defaultValue={order.phone} required /></div><div className="field"><label>이메일</label><input name="email" type="email" defaultValue={order.email} required /></div>{order.address && <><div className="field"><label>우편번호</label><input name="postalCode" defaultValue={order.address.postalCode} required /></div><div className="field"><label>기본 주소</label><input name="address" defaultValue={order.address.address} required /></div><div className="field field--full"><label>상세 주소</label><input name="addressDetail" defaultValue={order.address.addressDetail} required /></div></>}</div>{order.pickup && <p className="field__hint">픽업: {order.pickup.name} · {order.pickup.date} {order.pickup.startsAt.slice(0,5)}–{order.pickup.endsAt.slice(0,5)}</p>}<p className="field__hint">현금영수증: {order.cashReceiptType === 'none' ? '미신청' : `${order.cashReceiptType === 'personal' ? '소득공제' : '지출증빙'} · ${order.cashReceiptIdentifier}`}</p><Button type="submit" variant="secondary">주문자 정보 저장</Button></form>
          <h2>상품별 제작 정보</h2>{order.items.map((item, index) => <article className="admin-custom-item" key={item.id}><div className="admin-custom-item__title"><span>{item.itemType === 'shirt' ? <Shirt size={17} /> : <ShoppingBag size={17} />}</span><strong>{index + 1}. {item.productName} · {item.initialText}</strong><b>{item.lineAmount.toLocaleString('ko-KR')}원</b></div><dl className="info-list"><div><dt>옵션</dt><dd>{[item.size, item.gender].filter(Boolean).join(' · ') || '없음'}</dd></div><div><dt>스티커</dt><dd>{item.stickerSelected ? item.stickerCategories.join(', ') || '선택' : '미선택'}</dd></div><div><dt>좋아하는 색상</dt><dd>{item.favoriteColors || '-'}</dd></div><div><dt>동물·물건</dt><dd>{item.favoriteThings || '-'}</dd></div><div><dt>분위기</dt><dd>{item.desiredMood || '-'}</dd></div><div><dt>인스타그램</dt><dd>{item.instagramReference || '-'}</dd></div><div><dt>기타 요청</dt><dd>{item.extraRequest || '-'}</dd></div></dl>{item.images.length > 0 && <div className="admin-image-grid">{item.images.map((image) => <a href={image.url} target="_blank" rel="noreferrer" key={image.id}><img src={image.url} alt="주문 디자인 참고" /><span>원본 보기 <ExternalLink size={12} /></span></a>)}</div>}</article>)}
          <div className="summary-box"><div className="summary-line"><span>상품 합계</span><strong>{order.subtotalAmount.toLocaleString('ko-KR')}원</strong></div><div className="summary-line"><span>배송비</span><strong>{order.shippingFee ? `${order.shippingFee.toLocaleString('ko-KR')}원` : '무료'}</strong></div><div className="summary-line summary-line--total"><span>최종 입금액</span><strong>{order.totalAmount.toLocaleString('ko-KR')}원</strong></div></div>
        </div>
        <div className="admin-side-stack"><form className="admin-panel admin-state-form" action={updateOrderAction}>
          <input type="hidden" name="orderId" value={order.id} /><input type="hidden" name="orderNumber" value={order.orderNumber} />
          <h2>상태 변경</h2><div className="field"><label>주문 상태</label><select name="orderState" defaultValue={order.orderState}>{Object.entries(orderStateLabel).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></div><div className="field"><label>입금 상태</label><select name="paymentState" defaultValue={order.paymentState}>{Object.entries(paymentStateLabel).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></div><div className="field"><label>확인 필요 사유</label><select name="paymentReviewReason" defaultValue={order.paymentReviewReason ?? ''}><option value="">해당 없음</option><option>금액 불일치</option><option>입금자명 불일치</option><option>금액 및 입금자명 불일치</option></select></div><div className="field"><label>취소 사유</label><input name="cancellationReason" defaultValue={order.cancellationReason ?? ''} placeholder="예: 미입금 취소" /></div>
          {order.fulfillmentType === 'shipping' && <><h2>배송 정보</h2><div className="form-grid"><div className="field"><label>택배사 코드</label><input name="carrierCode" defaultValue={order.shipment?.carrierCode ?? ''} /></div><div className="field"><label>택배사</label><input name="carrierName" defaultValue={order.shipment?.carrierName ?? ''} placeholder="CJ대한통운" /></div><div className="field field--full"><label>송장번호</label><input name="trackingNumber" defaultValue={order.shipment?.trackingNumber ?? ''} /></div></div></>}
          <p className="field__hint">미입금 주문은 취소 사유에 ‘미입금’을 입력하고 주문 상태를 취소로 변경합니다. 자동 취소되지 않습니다.</p><Button type="submit">변경 내용 저장</Button>
        </form>{order.saleKind === 'live' ? <form className="admin-panel admin-email-resend" action={resendOrderEmailAction}><input type="hidden" name="orderId" value={order.id} /><input type="hidden" name="orderNumber" value={order.orderNumber} /><h2>이메일 재발송</h2><select name="eventType" aria-label="재발송할 이메일"><option value="order_received">주문 접수</option>{order.paymentState === 'paid' && <option value="payment_confirmed">입금 확인</option>}{order.orderState === 'cancelled' && <option value="order_cancelled">주문 취소</option>}{order.shipment?.trackingNumber && <option value="shipment_started">배송 시작</option>}{order.orderState === 'completed' && <option value="delivery_completed">완료</option>}</select><Button type="submit" variant="secondary">발송 대기열에 추가</Button></form> : <section className="admin-panel"><h2>테스트 이메일</h2><p className="field__hint">테스트 주문은 실제 이메일을 발송하지 않습니다.</p></section>}</div>
      </div>
    </>
  )
}
